using System;
using System.Collections.Generic;
using System.Net.Http;
using Windows.Data.Json;

namespace YouTube
{
    // Timed-text (subtitle) support: reads the caption tracks the video ships with, plus the
    // machine-translation languages YouTube offers for them, and turns a chosen track into cues.
    public static class Subtitles
    {
        public sealed class SubtitleTrack
        {
            public string LanguageCode { get; set; }
            public string Name { get; set; }
            public string BaseUrl { get; set; }
            public bool IsAutoGenerated { get; set; }
            public bool IsTranslatable { get; set; }

            // Set when this entry is "track X machine-translated into Y".
            public string TranslationLanguageCode { get; set; }
            public string TranslationLanguageName { get; set; }

            public string DisplayName
            {
                get
                {
                    if (!string.IsNullOrEmpty(TranslationLanguageName))
                    {
                        return TranslationLanguageName;
                    }

                    return IsAutoGenerated ? Name + " (auto)" : Name;
                }
            }
        }

        public sealed class TranslationLanguage
        {
            public string LanguageCode { get; set; }
            public string Name { get; set; }
        }

        public sealed class SubtitleCue
        {
            public TimeSpan Start { get; set; }
            public TimeSpan End { get; set; }
            public string Text { get; set; }
        }

        public sealed class TrackList
        {
            public List<SubtitleTrack> Tracks = new List<SubtitleTrack>();
            public List<TranslationLanguage> TranslationLanguages = new List<TranslationLanguage>();

            public bool HasAny { get { return Tracks.Count > 0; } }

            // Machine translation is only offered when at least one track allows it.
            public bool CanTranslate
            {
                get
                {
                    if (TranslationLanguages.Count == 0)
                    {
                        return false;
                    }

                    foreach (var track in Tracks)
                    {
                        if (track.IsTranslatable)
                        {
                            return true;
                        }
                    }

                    return false;
                }
            }

            public SubtitleTrack TranslationSource
            {
                get
                {
                    foreach (var track in Tracks)
                    {
                        if (track.IsTranslatable)
                        {
                            return track;
                        }
                    }

                    return null;
                }
            }
        }

        private static readonly HttpClient _http = new HttpClient();

        // Reads captions.playerCaptionsTracklistRenderer out of a /player response. Returns an
        // empty list rather than throwing when the video has no captions.
        public static TrackList ParseTracks(JsonObject playerRoot)
        {
            var result = new TrackList();

            try
            {
                if (playerRoot == null || !playerRoot.ContainsKey("captions"))
                {
                    return result;
                }

                var captions = playerRoot.GetNamedObject("captions");
                if (!captions.ContainsKey("playerCaptionsTracklistRenderer"))
                {
                    return result;
                }

                var renderer = captions.GetNamedObject("playerCaptionsTracklistRenderer");

                if (renderer.ContainsKey("captionTracks"))
                {
                    foreach (var value in renderer.GetNamedArray("captionTracks"))
                    {
                        var track = ParseTrack(value.GetObject());
                        if (track != null)
                        {
                            result.Tracks.Add(track);
                        }
                    }
                }

                if (renderer.ContainsKey("translationLanguages"))
                {
                    foreach (var value in renderer.GetNamedArray("translationLanguages"))
                    {
                        var language = value.GetObject();
                        var name = ReadText(language, "languageName");
                        if (!language.ContainsKey("languageCode") || string.IsNullOrEmpty(name))
                        {
                            continue;
                        }

                        result.TranslationLanguages.Add(new TranslationLanguage
                        {
                            LanguageCode = language.GetNamedString("languageCode"),
                            Name = name
                        });
                    }
                }

                System.Diagnostics.Debug.WriteLine(
                    "[Subtitles] " + result.Tracks.Count + " track(s), "
                    + result.TranslationLanguages.Count + " translation language(s)");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("[Subtitles] Track parsing failed: " + ex.Message);
            }

            return result;
        }

        private static SubtitleTrack ParseTrack(JsonObject track)
        {
            try
            {
                if (!track.ContainsKey("baseUrl"))
                {
                    return null;
                }

                var name = ReadText(track, "name");
                var languageCode = track.ContainsKey("languageCode")
                    ? track.GetNamedString("languageCode")
                    : string.Empty;

                return new SubtitleTrack
                {
                    BaseUrl = track.GetNamedString("baseUrl"),
                    LanguageCode = languageCode,
                    Name = string.IsNullOrEmpty(name) ? languageCode : name,
                    // kind == "asr" marks YouTube's own speech recognition.
                    IsAutoGenerated = track.ContainsKey("kind")
                        && string.Equals(track.GetNamedString("kind"), "asr", StringComparison.Ordinal),
                    IsTranslatable = track.ContainsKey("isTranslatable") && track.GetNamedBoolean("isTranslatable")
                };
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("[Subtitles] Bad track: " + ex.Message);
                return null;
            }
        }

        // InnerTube writes user-visible strings either as {"simpleText":...} or as a runs array.
        private static string ReadText(JsonObject owner, string key)
        {
            if (owner == null || !owner.ContainsKey(key))
            {
                return string.Empty;
            }

            var value = owner.GetNamedObject(key, null);
            if (value == null)
            {
                return string.Empty;
            }

            if (value.ContainsKey("simpleText"))
            {
                return value.GetNamedString("simpleText");
            }

            if (value.ContainsKey("runs"))
            {
                var text = string.Empty;
                foreach (var run in value.GetNamedArray("runs"))
                {
                    var runObject = run.GetObject();
                    if (runObject.ContainsKey("text"))
                    {
                        text += runObject.GetNamedString("text");
                    }
                }
                return text;
            }

            return string.Empty;
        }

        // Downloads and parses one track. The json3 format is asked for explicitly because it is
        // far simpler to read than the default XML and carries the timings in milliseconds.
        public static async System.Threading.Tasks.Task<List<SubtitleCue>> GetCuesAsync(SubtitleTrack track)
        {
            var cues = new List<SubtitleCue>();

            if (track == null || string.IsNullOrEmpty(track.BaseUrl))
            {
                return cues;
            }

            try
            {
                var url = track.BaseUrl + "&fmt=json3";
                if (!string.IsNullOrEmpty(track.TranslationLanguageCode))
                {
                    url += "&tlang=" + Uri.EscapeDataString(track.TranslationLanguageCode);
                }

                var response = await _http.GetAsync(new Uri(url));
                if (!response.IsSuccessStatusCode)
                {
                    System.Diagnostics.Debug.WriteLine(
                        "[Subtitles] Download returned " + (int)response.StatusCode);
                    return cues;
                }

                var body = await response.Content.ReadAsStringAsync();

                JsonObject root;
                if (!JsonObject.TryParse(body, out root) || !root.ContainsKey("events"))
                {
                    return cues;
                }

                foreach (var value in root.GetNamedArray("events"))
                {
                    var cue = ParseCue(value.GetObject());
                    if (cue != null)
                    {
                        cues.Add(cue);
                    }
                }

                cues.Sort((a, b) => a.Start.CompareTo(b.Start));
                System.Diagnostics.Debug.WriteLine(
                    "[Subtitles] " + cues.Count + " cue(s) for " + track.DisplayName);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("[Subtitles] Download failed: " + ex.Message);
            }

            return cues;
        }

        private static SubtitleCue ParseCue(JsonObject cueEvent)
        {
            try
            {
                // Events without segs are window/style definitions, not text.
                if (!cueEvent.ContainsKey("segs") || !cueEvent.ContainsKey("tStartMs"))
                {
                    return null;
                }

                var text = string.Empty;
                foreach (var seg in cueEvent.GetNamedArray("segs"))
                {
                    var segment = seg.GetObject();
                    if (segment.ContainsKey("utf8"))
                    {
                        text += segment.GetNamedString("utf8");
                    }
                }

                text = text.Trim();
                if (string.IsNullOrEmpty(text) || text == "\n")
                {
                    return null;
                }

                var start = cueEvent.GetNamedNumber("tStartMs");
                // Auto-generated tracks sometimes omit the duration; give those a sane fallback.
                var duration = cueEvent.ContainsKey("dDurationMs")
                    ? cueEvent.GetNamedNumber("dDurationMs")
                    : 3000;

                return new SubtitleCue
                {
                    Start = TimeSpan.FromMilliseconds(start),
                    End = TimeSpan.FromMilliseconds(start + duration),
                    Text = text
                };
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("[Subtitles] Bad cue: " + ex.Message);
                return null;
            }
        }
    }
}
